name: hourlynotes
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Core
  provider: ^6.0.5
  go_router: ^12.1.1

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  # google_sign_in: ^7.2.0

  # Google APIs
  # googleapis: ^15.0.0
  # googleapis_auth: ^1.4.1
  i_google_drive: ^1.0.0
  # path: ^1.9.0          # helpful for paths
  
  
  # Local Notifications
  flutter_local_notifications: ^17.0.0

   # Database
   # isar: ^3.1.0+1
   # isar_flutter_libs: ^3.1.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  uuid: ^4.5.0

  # UI
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  logger: ^2.6.2
  font_awesome_flutter: ^10.12.0
  get: ^4.7.3
  another_flushbar: ^1.12.32

  table_calendar: ^3.1.2  # or latest version
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  # isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
